### ISSUE TITLE
Where to submit patches?

### ISSUE THREAD

**Issue by barefootcoder** [perlancar/perl-Sys-RunAlone-Flexible#1]
Are you planning to fold `Sys::RunAlone::Flexible` back into `Sys::RunAlone`?  I ask because there are some POD errors (which are now in both) that I would be happy to submit a patch for.  If I submit them here, will they eventually make it back there?

**Comment by perlancar** [comment]
I plan to, but for now the easiest thing would be to patch Sys::RunAlone::Flexible. I will merge changes to Sys::RunAlone (or even make Sys::RunAlone::Flexible the new Sys::RunAlone) later in the future.
